# Vizhelper github build workflow
name: BuildArtefact[main]
on:
  push:
    branches: [ main ]
jobs:
  # Build vizhelper
  build-vizhelper:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.4']
    steps:
    - uses: actions/checkout@v3
    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'VizHelper'
        love_version: ${{ matrix.love_version }}
        source_dir: '/'
    # Upload the resulting artifacts
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: hw_macos-build
    #     path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_love-build
        path: ${{ steps.love-build.outputs.love-filename }}